#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import process from 'process'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const ICONS_DIR = path.join(__dirname, '..', 'epicenter-icons')
const OUTPUT_FILE = path.join(__dirname, '..', 'index.js')

/**
 * Generate an index file that exports all icons for destructured imports
 */
function generateIndex() {
  console.log('🚀 Generating index file for icon exports...')

  // Read all .js files from epicenter-icons directory
  const files = fs.readdirSync(ICONS_DIR)
    .filter(file => file.endsWith('.js'))
    .sort()

  if (files.length === 0) {
    console.error('❌ No icon files found in epicenter-icons directory')
    process.exit(1)
  }

  console.log(`📦 Found ${files.length} icon files`)

  // Generate export statements
  const exports = files.map(file => {
    const componentName = path.basename(file, '.js')
    return `export { default as ${componentName} } from './epicenter-icons/${componentName}.js'`
  })

  // Create the index file content
  const indexContent = [
    '/**',
    ' * Epicenter Icons',
    ' * Auto-generated index file for icon exports',
    ' * DO NOT EDIT MANUALLY - Generated by scripts/generate-index.mjs',
    ' */',
    '',
    ...exports,
    ''
  ].join('\n')

  // Write the index file
  fs.writeFileSync(OUTPUT_FILE, indexContent, 'utf8')

  console.log(`✅ Generated ${OUTPUT_FILE}`)
  console.log(`📝 Exported ${files.length} icons`)
  console.log('')
  console.log('Example usage:')
  console.log('  import { Coffee02, ArrowRight01 } from \'@ericpitcock/epicenter-icons\'')
}

// Run the generator
try {
  generateIndex()
} catch (error) {
  console.error('❌ Error generating index:', error)
  process.exit(1)
}
