import { execFile } from 'child_process'
import fs from 'fs'
import path, { join, resolve } from 'path'
import process from 'process'
import { fileURLToPath } from 'url'
import { promisify } from 'util'

import fsExtra from 'fs-extra'
import { glob } from 'glob'
import yaml from 'js-yaml'
import * as sass from 'sass'

const { ensureDir, copyFile } = fsExtra
const execFileAsync = promisify(execFile)

// Get __dirname equivalent in ESM
const __filename = fileURLToPath(import.meta.url)
const __dirname = resolve(__filename, '..')

// Define paths
const packageDir = resolve(__dirname, '..')
const tokensDir = join(packageDir, 'tokens')
const distDir = join(packageDir, 'dist')
const distCSS = join(distDir, 'epicenter-design-system.css')
const distThemeCSS = join(distDir, 'theme.css')
const seedsSCSS = join(packageDir, 'scss/theme/_seeds.scss')

// The landing site serves its own copy of both stylesheets; writing them from
// here keeps the two from drifting.
const staticDir = resolve(packageDir, '../../static')

// SCSS mixins to copy — the package's public SCSS surface. Theming no longer
// needs SCSS at all (see tokens/theme.yaml), so only the shared helpers ship.
const mixinsToCopy = [
  join(packageDir, 'scss/mixins/_mixins.scss')
]

const watchMode = process.argv.includes('--watch')

const readYAML = file => yaml.load(fs.readFileSync(file, 'utf8'))

// ---------------------------------------------------------------------------
// Theme seeds (tokens/theme.yaml → _seeds.scss, @property preamble, theme.css)
// ---------------------------------------------------------------------------

/** Flat list of every seed, in file order, with its group attached. */
function loadSeeds() {
  const groups = readYAML(join(tokensDir, 'theme.yaml'))
  const seeds = []
  for (const group of groups) {
    for (const [name, seed] of Object.entries(group.seeds)) {
      seeds.push({ name: `--${name}`, group: group.group, ...seed })
    }
  }
  return { groups, seeds }
}

/**
 * The @property rules for every registered seed.
 *
 * Registration means a consumer's bad value (`--primary-color: #gg0000`) falls
 * back to the initial value instead of making every `oklch(from var(--primary-
 * color) …)` invalid at computed-value time — which would blank roughly a third
 * of the component layer. It also makes a `<color>` seed compute to a resolved
 * color, so a derivation from --accent-color does not textually nest two
 * relative-color functions.
 */
function propertyPreamble(seeds) {
  const rules = []
  for (const seed of seeds) {
    if (!seed.property) continue
    const initial = seed.initial ?? seed.value
    // The spec requires a computationally independent initial-value; a var()
    // there registers nothing, silently.
    if (/var\(/.test(initial)) {
      throw new Error(
        `theme.yaml: ${seed.name} is registered but its initial-value "${initial}" ` +
        'contains var(). Give it a literal `initial`.'
      )
    }
    rules.push(`@property ${seed.name}{syntax:"${seed.property}";inherits:true;initial-value:${initial}}`)
  }
  return rules.join('')
}

const wrapComment = (text, indent = '  ') =>
  text
    .trim()
    .split('\n')
    .map(line => `${indent} * ${line}`.replace(/\s+$/, ''))
    .join('\n')

/** The starter file a consumer copies. Every value is the shipped default. */
function themeStarter(groups, chartSequence) {
  let out = `/* Epicenter theme
 *
 * Copy this file into your app, edit the values, and load it AFTER the package
 * stylesheet:
 *
 *   import '@ericpitcock/epicenter-styles'
 *   import './theme.css'
 *
 * It is deliberately unlayered, so every line here beats the package defaults
 * regardless of specificity — no !important, no out-specifying selectors.
 *
 * Every value below is the shipped default; delete anything you do not change.
 * Colors may be written in any color space (hex, hsl, oklch, named): the
 * ramps derive with oklch(from …), which converts the origin first.
 *
 * Light and dark are not separate themes. Every derived token is a light-dark()
 * pair driven by color-scheme, so one set of seeds covers both modes.
 *
 * Generated by scripts/build.mjs from tokens/theme.yaml. Regenerate, do not edit.
 */
:root {
`

  for (const group of groups) {
    out += `  /* ---- ${group.group} ${'-'.repeat(Math.max(3, 66 - group.group.length))}\n`
    if (group.intro) out += `${wrapComment(group.intro)}\n`
    out += '   */\n'
    for (const [name, seed] of Object.entries(group.seeds)) {
      if (seed.comment) out += `  /*\n${wrapComment(seed.comment)}\n   */\n`
      out += `  --${name}: ${seed.value};\n`
    }
    out += '\n'
  }

  out += `  /* ---- Charts ${'-'.repeat(60)}
 * Series colors, in order. Highcharts reads them through --highcharts-color-N
 * and EpDonutChart indexes its arcs the same way. Two-argument light-dark()
 * entries differ per mode; single-value entries are the same in both.
 * --chart-sequence-count is derived from this list and is not a seed.
   */
`
  for (const [name, value] of Object.entries(chartSequence)) {
    const dark = value.dark ?? value.light
    const light = value.light ?? value.dark
    out += `  --${name}: light-dark(${light}, ${dark});\n`
  }

  out += `}

/* Not here on purpose: the density scales — --space--*, --control-height--*,
 * --font-size--*, --z-index--*, --shadow--*, --duration--*. They are global
 * tokens like any other and can be overridden the same way, but they are not
 * part of a brand theme. */
`
  return out
}

function buildThemeSeeds() {
  console.log('🌱 Building theme seeds...')
  const { groups, seeds } = loadSeeds()

  let scss = `/* stylelint-disable */\n/* DO NOT EDIT DIRECTLY — generated from tokens/theme.yaml */\n:root {\n`
  for (const seed of seeds) scss += `  ${seed.name}: ${seed.value};\n`
  scss += '}\n'
  fs.writeFileSync(seedsSCSS, scss)
  console.log(`  SCSS file generated: ${seedsSCSS}`)

  const preamble = propertyPreamble(seeds)

  const chartSequence = readYAML(join(tokensDir, 'color/chart-sequence.yaml'))
  const starter = themeStarter(groups, chartSequence)
  fs.mkdirSync(distDir, { recursive: true })
  fs.writeFileSync(distThemeCSS, starter)
  if (fs.existsSync(staticDir)) fs.writeFileSync(join(staticDir, 'theme.css'), starter)
  console.log(`  Theme starter generated: ${distThemeCSS}`)

  console.log('✅ Theme seeds built')
  return { seedNames: new Set(seeds.map(seed => seed.name)), preamble }
}

// ---------------------------------------------------------------------------
// Build color tokens (YAML → SCSS)
// ---------------------------------------------------------------------------

function loadYAMLFiles(pattern) {
  const yamlData = {}
  const fullPattern = resolve(__dirname, pattern)
  const files = glob.sync(fullPattern)
  files.forEach(file => {
    try {
      yamlData[file] = readYAML(file)
    } catch (error) {
      console.error('Error:', error)
    }
  })
  return yamlData
}

// The primitive ramps hold unwrapped HSL channel triplets, so referencing one
// without an hsl() wrapper produces an invalid value that fails silently.
const RAMP_TOKEN = /var\(\s*--(?:gray|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\d+\s*\)/

// `262 51% 58%` standing on its own is an HSL triplet, not a color. Ramp tokens
// are stored that way on purpose so they can be reused inside hsl(), but a themed
// token is substituted into light-dark(), which takes colors — so a bare triplet
// there produces a declaration the browser drops. Nothing errors; the element just
// falls back to its initial value, which for an SVG fill is black.
const BARE_TRIPLET = /(?:^|[\s,])-?[\d.]+(?:deg)?\s+-?[\d.]+%\s+-?[\d.]+%/

// Strip color-function calls, allowing one level of nesting inside each —
// hsl(var(--x)), oklch(from var(--x) calc(l + 0.08) c h). stripColorFns repeats
// until nothing changes, so an outer light-dark(oklch(…), oklch(…)) goes once
// its arguments have.
const COLOR_FN = /\b(?:hsla?|rgba?|oklch|oklab|light-dark)\(([^()]|\([^()]*\))*\)/g

const stripColorFns = value => {
  let out = String(value)
  let previous
  do {
    previous = out
    out = out.replace(COLOR_FN, ' ')
  } while (out !== previous)
  return out
}

function assertIsColor(key, value, filePath, seedNames) {
  // Anything already inside a color function is fine; strip those and see what is left.
  const bare = stripColorFns(value)

  if (RAMP_TOKEN.test(bare)) {
    throw new Error(
      `${path.basename(filePath)}: "${key}: ${value}" references a raw HSL triplet ` +
      'without an hsl() wrapper — the resulting value is invalid. Write hsl(var(--…)).'
    )
  }

  if (BARE_TRIPLET.test(bare)) {
    throw new Error(
      `${path.basename(filePath)}: "${key}: ${value}" is a bare HSL triplet, but a ` +
      'themed token becomes an argument to light-dark(), which takes colors. ' +
      'Write hsl(…).'
    )
  }

  // A derivation from a seed that does not exist renders as transparent black
  // and nothing errors, so check the origin names something theme.yaml declares.
  const origins = String(value).matchAll(/\bfrom\s+var\(\s*(--[a-zA-Z0-9-]+)\s*\)/g)
  for (const [, origin] of origins) {
    if (!seedNames.has(origin)) {
      throw new Error(
        `${path.basename(filePath)}: "${key}" derives from ${origin}, which tokens/theme.yaml ` +
        'does not declare. Relative-color origins must be seeds.'
      )
    }
  }
}

/**
 * OKLCH lightness of an achromatic sRGB color whose channels are all `p` (0–1).
 *
 * For a pure gray the LMS cone responses equal the relative luminance Y (each
 * row of the sRGB→LMS matrix sums to 1), and the OKLab L coefficients sum to 1,
 * so L = cbrt(Y). The sRGB transfer curve is a 2.4 power above the linear toe,
 * which collapses cbrt(((p + 0.055) / 1.055) ^ 2.4) to a 0.8 power.
 */
const oklchLightness = p =>
  p <= 0.04045 ? Math.cbrt(p / 12.92) : ((p + 0.055) / 1.055) ** 0.8

/**
 * The `neutral(N)` value form: the lightness of the gray ramp step `gray-N`,
 * applied to the chroma and hue of --neutral-color.
 *
 *   neutral(430)        →  oklch(from var(--neutral-color) 0.2591 c h)
 *   neutral(430, 0.85)  →  oklch(from var(--neutral-color) 0.2591 c h / 0.85)
 *
 * With the default seed (chroma 0) every step resolves to the same gray the
 * ramp holds, so the derivation is invisible until a consumer adds chroma. The
 * lightness is computed here rather than typed into themes.yaml because the
 * sRGB→OKLCH curve is not linear and nothing would catch a wrong constant.
 */
const NEUTRAL = /\bneutral\(\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)/g

const resolveNeutral = (value, key, filePath, grayscale) =>
  String(value).replace(NEUTRAL, (_, step, alpha) => {
    const triplet = grayscale[`gray-${step}`]
    if (!triplet) {
      throw new Error(
        `${path.basename(filePath)}: "${key}" references gray-${step}, which grayscale.yaml does not define`
      )
    }
    const percent = String(triplet).match(/([\d.]+)%\s*$/)?.[1]
    const lightness = Math.round(oklchLightness(Number(percent) / 100) * 1e4) / 1e4
    return `oklch(from var(--neutral-color) ${lightness} c h${alpha ? ` / ${alpha}` : ''})`
  })

function writeCSS(filePath, yamlData, { grayscale, seedNames }) {
  let cssOutput = `/* stylelint-disable no-duplicate-selectors */\n/* DO NOT EDIT DIRECTLY */\n`

  // Stylesheets that walk a token family in order — the Highcharts palette bridge
  // in _charts.scss is the one that does — need the names, not just the count.
  // Exporting them from the generated partial keeps the YAML the single place the
  // family is written down, so a loop over it cannot fall out of step with it.
  const names = Object.keys(yamlData).map(key => `'${key}'`).join(', ')
  cssOutput += `$names: (${names});\n\n`

  const fileName = resolve(__dirname, '..', 'scss', 'color', `_${path.basename(filePath).replace('.yaml', '.scss')}`)

  // Themed tokens are recognised by their shape — a { light, dark } pair — not by
  // filename, so a new themed token file gets light-dark() automatically.
  const isThemed = Object.values(yamlData).some(
    value => value && typeof value === 'object' && ('dark' in value || 'light' in value)
  )

  cssOutput += `:root {\n`

  Object.entries(yamlData).forEach(([key, value]) => {
    if (!isThemed) {
      cssOutput += `  --${key}: ${value};\n`
      return
    }

    const darkValue = resolveNeutral(value.dark ?? value.light, key, filePath, grayscale)
    const lightValue = resolveNeutral(value.light ?? value.dark, key, filePath, grayscale)
    assertIsColor(key, darkValue, filePath, seedNames)
    assertIsColor(key, lightValue, filePath, seedNames)
    cssOutput += `  --${key}: light-dark(${lightValue}, ${darkValue});\n`
  })

  cssOutput += `}\n`

  fs.writeFileSync(fileName, cssOutput)
  console.log(`  SCSS file generated: ${fileName}`)
}

function buildColorTokens(seedNames) {
  console.log('🎨 Building color tokens...')
  try {
    const yamlFilesData = loadYAMLFiles('../tokens/color/*.yaml')
    const grayscale = readYAML(join(tokensDir, 'color/grayscale.yaml'))
    for (const [filePath, yamlData] of Object.entries(yamlFilesData)) {
      writeCSS(filePath, yamlData, { grayscale, seedNames })
    }
    console.log('✅ Color tokens built')
  } catch (error) {
    console.error('❌ Color token build failed:', error)
    throw error
  }
}

// ---------------------------------------------------------------------------
// Compile SCSS → CSS
// ---------------------------------------------------------------------------

/**
 * Cascade layers, least- to most-specific in intent.
 *
 * Consumer CSS written outside a layer beats layered CSS regardless of
 * specificity, so overriding a component no longer means out-specifying
 * selectors like `.ep-menu__item .ep-button--menu-item`.
 *
 * Sass forbids `@use` inside `@layer`, so each group is compiled on its own and
 * wrapped here rather than in index.scss. Two chunks may share a layer name —
 * the theme seeds and the color tokens both land in epicenter.tokens — and the
 * browser merges them.
 */
const LAYERS = [
  { name: 'epicenter.reset', use: 'scss/reset' },
  { name: 'epicenter.tokens', use: 'scss/theme' },
  { name: 'epicenter.tokens', use: 'scss/color' },
  { name: 'epicenter.base', use: 'scss/type' },
  { name: 'epicenter.components', use: 'scss/components' },
  { name: 'epicenter.utilities', use: 'scss/utilities' }
]

async function compileSass(preamble) {
  console.log('🎨 Compiling SCSS...')
  await ensureDir(distDir)

  try {
    const order = [...new Set(LAYERS.map(layer => layer.name))].join(',')

    // The @property registrations sit outside every layer: registration is not
    // cascaded, and keeping it out of @layer sidesteps the question entirely.
    const chunks = [`@layer ${order};`, preamble]

    for (const layer of LAYERS) {
      const { css } = sass.compileString(`@use '${layer.use}';`, {
        loadPaths: [packageDir],
        style: 'compressed'
      })

      // @charset may only appear once, at the very start of a stylesheet.
      const body = css.replace(/^@charset\s+"[^"]*";\s*/i, '').trim()
      if (body) chunks.push(`@layer ${layer.name}{${body}}`)
    }

    const css = `${chunks.filter(Boolean).join('\n')}\n`
    fs.writeFileSync(distCSS, css)

    // The landing site serves its own copy; write it here so the two cannot
    // drift (it was previously only produced by a manual watch script).
    if (fs.existsSync(staticDir)) {
      fs.writeFileSync(join(staticDir, 'epicenter-design-system.css'), css)
    }

    console.log(`✅ SCSS compiled into ${new Set(LAYERS.map(layer => layer.name)).size} cascade layers: ${distCSS}`)
  } catch (error) {
    console.error('❌ SCSS compilation failed:', error.message || error)
    throw error
  }
}

// ---------------------------------------------------------------------------
// Copy SCSS mixins
// ---------------------------------------------------------------------------

async function copyMixins() {
  console.log('📂 Copying SCSS mixins...')
  for (const mixin of mixinsToCopy) {
    const dest = join(distDir, 'mixins', mixin.split('/').pop())
    await ensureDir(join(distDir, 'mixins'))
    await copyFile(mixin, dest)
    console.log(`  Copied: ${mixin} → ${dest}`)
  }
  console.log('✅ Mixins copied')
}

// ---------------------------------------------------------------------------
// Validate the custom-property contract
// ---------------------------------------------------------------------------

async function validateProperties() {
  console.log('🔎 Validating custom-property contract...')
  const script = join(packageDir, 'scripts/validate-properties.mjs')
  try {
    const { stdout } = await execFileAsync(process.execPath, [script])
    console.log(stdout.trimEnd())
  } catch (error) {
    // The validator reports on stdout and signals failure through its exit code,
    // so surface the report before letting the build fail.
    if (error.stdout) console.log(error.stdout.trimEnd())
    if (error.stderr) console.error(error.stderr.trimEnd())
    throw new Error('custom-property contract validation failed')
  }
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

async function build() {
  console.log('🚀 Building styles package...')
  try {
    const { seedNames, preamble } = buildThemeSeeds()
    buildColorTokens(seedNames)
    await compileSass(preamble)
    await validateProperties()
    await copyMixins()
    console.log('🎉 Styles build complete!')
  } catch (err) {
    console.error('❌ Build failed:', err)
    process.exit(1)
  }
}

// Run the full build
await build()

// Optionally watch sources and rebuild
if (watchMode) {
  const chokidar = await import('chokidar')

  console.log('👀 Watching tokens and SCSS for changes...')

  // Watch the SCSS too, not just the tokens — this is now the only watch script,
  // and a component edit needs to reach dist the same way a token edit does.
  const watcher = chokidar.default.watch([
    resolve(__dirname, '../tokens/**/*.yaml'),
    resolve(__dirname, '../scss/**/*.scss'),
    resolve(__dirname, '../index.scss')
  ], {
    // scss/color/* and scss/theme/_seeds.scss are generated by this build;
    // watching them would loop.
    ignored: [
      resolve(__dirname, '../scss/color/*.scss'),
      seedsSCSS
    ]
  })

  watcher.on('change', async () => {
    console.log('Change detected, rebuilding...')
    await build()
  })
}
