import fs from 'fs'
import path, { join, resolve } from 'path'
import { fileURLToPath } from 'url'

import { copy, ensureDir, remove } from 'fs-extra'

// Get __dirname equivalent in ESM
const __filename = fileURLToPath(import.meta.url)
const __dirname = resolve(__filename, '..')

const packageDir = resolve(__dirname, '..')
const srcDir = resolve(packageDir, 'src')
const distDir = resolve(packageDir, 'dist')
const componentsDir = resolve(srcDir, 'components')

// ---------------------------------------------------------------------------
// Generate component exports
// ---------------------------------------------------------------------------

function generateComponentExports() {
  if (!fs.existsSync(componentsDir)) {
    console.error(`❌ Components directory not found at: ${componentsDir}`)
    return
  }

  // Output file (index.js in components directory)
  const outputFile = join(componentsDir, 'index.js')

  // Helper function to recursively find all .vue files
  const findVueFiles = (dir) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    const files = entries.flatMap((entry) => {
      const fullPath = join(dir, entry.name)
      return entry.isDirectory() ? findVueFiles(fullPath) : fullPath
    })
    return files.filter((file) => file.endsWith('.vue'))
  }

  // Find all .vue files in the components directory
  const vueFiles = findVueFiles(componentsDir)

  if (vueFiles.length === 0) {
    console.log('⚠️ No Vue components found. Skipping export generation.')
    return
  }

  // Generate import statements and named exports
  const importStatements = vueFiles.map((filePath) => {
    const relativePath = `./${path.relative(componentsDir, filePath).replace(/\\/g, '/')}`
    const componentName = path.basename(filePath, '.vue')
    return `import ${componentName} from '${relativePath}'`
  })

  const exportNames = vueFiles.map((filePath) => path.basename(filePath, '.vue'))
  const namedExports = `export {\n  ${exportNames.join(',\n  ')}\n}`
  const defaultExport = `export default {\n  ${exportNames.join(',\n  ')}\n}`
  const outputContent = `/* eslint-disable perfectionist/sort-imports */\n// Generated by scripts/build.mjs — do not edit directly\n\n${importStatements.join('\n')}\n\n${namedExports}\n\n${defaultExport}\n`

  // Write the output file
  fs.writeFileSync(outputFile, outputContent)

  console.log(`✅ Export file generated at: ${outputFile}`)
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

console.log('🚀 Building package...')

// Generate component exports
generateComponentExports()

// Ensure dist is clean
await remove(distDir)
await ensureDir(distDir)

// Copy `index.js`
await copy(join(srcDir, 'index.js'), join(distDir, 'index.js'))

// Copy `composables/` as is
await copy(join(srcDir, 'composables'), join(distDir, 'composables'))

// Copy `plugins/` as is
await copy(join(srcDir, 'plugins'), join(distDir, 'plugins'))

// Copy `components/` while excluding `*.notes.md` and `*.stories.js`
await copy(join(srcDir, 'components'), join(distDir, 'components'), {
  filter: (src) => !src.endsWith('.notes.md') && !src.endsWith('.stories.js')
})

console.log('✅ Build complete! Files copied to dist/')
