import { execFileSync } from 'child_process'
import fs from 'fs'
import path, { join, resolve } from 'path'
import { fileURLToPath } from 'url'

// Get __dirname equivalent in ESM
const __filename = fileURLToPath(import.meta.url)
const __dirname = resolve(__filename, '..')

const packageDir = resolve(__dirname, '..')
const srcDir = resolve(packageDir, 'src')
const distDir = resolve(packageDir, 'dist')
const componentsDir = resolve(srcDir, 'components')

// ---------------------------------------------------------------------------
// Generate component exports
// ---------------------------------------------------------------------------

function generateComponentExports() {
  if (!fs.existsSync(componentsDir)) {
    console.error(`❌ Components directory not found at: ${componentsDir}`)
    return
  }

  // Output file (index.ts in components directory)
  const outputFile = join(componentsDir, 'index.ts')

  // Helper function to recursively find all .vue files
  const findVueFiles = (dir) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    const files = entries.flatMap((entry) => {
      const fullPath = join(dir, entry.name)
      return entry.isDirectory() ? findVueFiles(fullPath) : fullPath
    })
    return files.filter((file) => file.endsWith('.vue'))
  }

  // Find all .vue files in the components directory
  const vueFiles = findVueFiles(componentsDir)

  if (vueFiles.length === 0) {
    console.log('⚠️ No Vue components found. Skipping export generation.')
    return
  }

  // Generate import statements and named exports
  const importStatements = vueFiles.map((filePath) => {
    const relativePath = `./${path.relative(componentsDir, filePath).replace(/\\/g, '/')}`
    const componentName = path.basename(filePath, '.vue')
    return `import ${componentName} from '${relativePath}'`
  })

  const exportNames = vueFiles.map((filePath) => path.basename(filePath, '.vue'))
  const namedExports = `export {\n  ${exportNames.join(',\n  ')}\n}`

  /**
   * The default export is annotated rather than inferred.
   *
   * An inferred object literal type would name each component's internal
   * `Props`/`CarouselImage`/etc. interface, and those are not exported from
   * their SFCs — declaration emit fails with TS4082 on every one. This export
   * only exists to feed the install plugin's `app.component(name, component)`
   * loop, so the precise shape buys nothing; the named exports above keep their
   * full types.
   */
  const defaultExport = `const components: Record<string, Component> = {\n  ${exportNames.join(',\n  ')}\n}\n\nexport default components`
  const outputContent = `/* eslint-disable perfectionist/sort-imports */\n// Generated by scripts/build.mjs — do not edit directly\n\nimport type { Component } from 'vue'\n\n${importStatements.join('\n')}\n\n${namedExports}\n\n${defaultExport}\n`

  // Write the output file
  fs.writeFileSync(outputFile, outputContent)

  console.log(`✅ Export file generated at: ${outputFile}`)
}

// ---------------------------------------------------------------------------
// Normalise the declarations vue-tsc emits
// ---------------------------------------------------------------------------

/**
 * vue-tsc names an SFC's declaration after the whole filename, so
 * `EpButton.vue` emits `EpButton.vue.d.ts` and every declaration that imports it
 * writes `from './EpButton.vue'`. Neither matches the JS Vite emitted
 * (`EpButton.mjs`), so TypeScript would resolve the `./components/*` export to
 * nothing.
 *
 * Dropping the `.vue` from both the filenames and the specifiers inside them
 * puts the two halves back in sync. dist/ mirrors src/, so no path rewriting
 * beyond the suffix is needed.
 */
function normaliseDeclarations() {
  const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = join(dir, entry.name)
    return entry.isDirectory() ? walk(fullPath) : [fullPath]
  })

  const declarations = walk(distDir).filter((file) => file.endsWith('.d.ts'))
  let renamed = 0

  for (const file of declarations) {
    const contents = fs.readFileSync(file, 'utf8')
    // Only ever appears in this codebase as an import specifier suffix.
    const rewritten = contents.replace(/\.vue(['"])/g, '$1')

    if (rewritten !== contents) fs.writeFileSync(file, rewritten)

    if (file.endsWith('.vue.d.ts')) {
      fs.renameSync(file, file.replace(/\.vue\.d\.ts$/, '.d.ts'))
      renamed++
    }
  }

  console.log(`✅ Declarations normalised (${declarations.length} files, ${renamed} renamed)`)
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

const run = (command, args) => execFileSync(command, args, { cwd: packageDir, stdio: 'inherit' })

console.log('🚀 Building package...')

generateComponentExports()

console.log('📦 Compiling with Vite...')
run('npx', ['vite', 'build'])

console.log('🧾 Emitting declarations with vue-tsc...')
run('npx', ['vue-tsc', '-p', 'tsconfig.build.json'])
normaliseDeclarations()

run('node', ['scripts/verify-dist.mjs'])

console.log('✅ Build complete!')
